// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsw4m1rqIV2eLL8ZLvrFT4vSF2WE-TsZw',
    appId: '1:1016577444638:web:cc044924a3eae56055570f',
    messagingSenderId: '1016577444638',
    projectId: 'fireauth-15028',
    authDomain: 'fireauth-15028.firebaseapp.com',
    storageBucket: 'fireauth-15028.firebasestorage.app',
    measurementId: 'G-ZT6JG28WJW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD46xcNbKU3Bxy4oPwzkWpxPz_8luZX7Ew',
    appId: '1:1016577444638:android:b42a9a7243c4b0d855570f',
    messagingSenderId: '1016577444638',
    projectId: 'fireauth-15028',
    storageBucket: 'fireauth-15028.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCM5Y9Pj5e6tdKyglcc4-0AV9NGh7ZOQ6A',
    appId: '1:1016577444638:ios:3ae0aa780fb7bc2555570f',
    messagingSenderId: '1016577444638',
    projectId: 'fireauth-15028',
    storageBucket: 'fireauth-15028.firebasestorage.app',
    iosBundleId: 'com.example.loginSignTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCM5Y9Pj5e6tdKyglcc4-0AV9NGh7ZOQ6A',
    appId: '1:1016577444638:ios:3ae0aa780fb7bc2555570f',
    messagingSenderId: '1016577444638',
    projectId: 'fireauth-15028',
    storageBucket: 'fireauth-15028.firebasestorage.app',
    iosBundleId: 'com.example.loginSignTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBsw4m1rqIV2eLL8ZLvrFT4vSF2WE-TsZw',
    appId: '1:1016577444638:web:2809802191da45ab55570f',
    messagingSenderId: '1016577444638',
    projectId: 'fireauth-15028',
    authDomain: 'fireauth-15028.firebaseapp.com',
    storageBucket: 'fireauth-15028.firebasestorage.app',
    measurementId: 'G-663HF0557G',
  );
}
